FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Fund Comparison Tool API

Fund Comparison Tool API is a simple API that allows users to query data on
mutual funds.

## Fund Performance [/performance/fund_symbol]

### GET: /performance/fund_symbol [GET]

### Retrieves the following fields of performance data for the given mutual fund:
1. Trailing returns
2. Historical returns
3. Hypothetical growth of $10000, invested 5 years ago

### Sources I scraped this data from:
1. [Morningstar](http://performance.morningstar.com/perform/Performance/fund/trailing-total-returns.action?&t=PRHSX&cur=&ops=clear&s=0P00001L8R&ndec=2&ep=true&align=q&annlz=true&comparisonRemove=false&loccat=&taxadj=&benchmarkSecId=&benchmarktype=)
2. [Yahoo Finance](https://finance.yahoo.com/quote/PRHSX/performance?p=PRHSX)
3. [Markets.ft](https://markets.ft.com/data/funds/ajax/US/get-comparison-panel?data={"comparisons":["PRHSX"],"openPanels":["Performance"]})

**HTTP Request:**
`link coming soon once I deploy`

+ Response 200 (application/json)

    + Body
    
            {
                  "trailing_returns": {
                    "1-Month": "1.57",
                    "3-Month": "6.31",
                    "6-Month": "7.75",
                    "YTD": "7.75",
                    "1-Year": "15.32",
                    "3-Year": "5.11",
                    "5-Year": "18.52",
                    "10-Year": "17.19",
                    "15-Year": "15.35"
                  },
                  "historical_returns": {
                    "PRHSX": {
                      "1996": "26.75",
                      "1997": "19.41",
                      "1998": "22.37",
                      "1999": "7.97",
                      "2000": "52.19",
                      "2001": "-5.97",
                      "2002": "-27.74",
                      "2003": "37.49",
                      "2004": "15.84",
                      "2005": "13.53",
                      "2006": "9.58",
                      "2007": "18.75",
                      "2008": "-28.77",
                      "2009": "32.17",
                      "2010": "16.33",
                      "2011": "11.01",
                      "2012": "31.93",
                      "2013": "51.40",
                      "2014": "31.94",
                      "2015": "12.98",
                      "2016": "-10.35",
                      "2017": "27.95"
                    },
                    "Category": {
                      "1996": "13.50",
                      "1997": "22.11",
                      "1998": "20.97",
                      "1999": "18.58",
                      "2000": "56.75",
                      "2001": "-11.26",
                      "2002": "-28.13",
                      "2003": "32.51",
                      "2004": "9.84",
                      "2005": "9.64",
                      "2006": "4.27",
                      "2007": "9.27",
                      "2008": "-23.43",
                      "2009": "22.48",
                      "2010": "8.38",
                      "2011": "7.66",
                      "2012": "21.55",
                      "2013": "48.17",
                      "2014": "27.25",
                      "2015": "8.05",
                      "2016": "-10.60",
                      "2017": "24.31"
                    }
                  },
                  "10000_growth_data": {
                    "2013-08-31": 10000,
                    "2013-09-30": 10580.968975,
                    "2013-10-31": 10739.581388,
                    "2013-11-30": 11316.857954,
                    "2013-12-31": 11509.645292,
                    "2014-01-31": 12170.752332,
                    "2014-02-28": 12949.343377,
                    "2014-03-31": 12198.627884,
                    "2014-04-30": 11826.258666,
                    "2014-05-31": 12314.125856,
                    "2014-06-30": 12734.287829,
                    "2014-07-31": 12845.799518,
                    "2014-08-31": 13749.842397,
                    "2014-09-30": 13656.252399,
                    "2014-10-31": 14544.36436,
                    "2014-11-30": 15064.093388,
                    "2014-12-31": 15185.620557,
                    "2015-01-31": 15840.03955,
                    "2015-02-28": 16849.583881,
                    "2015-03-31": 17311.917047,
                    "2015-04-30": 16829.481821,
                    "2015-05-31": 18203.086266,
                    "2015-06-30": 18263.392446,
                    "2015-07-31": 18761.464715,
                    "2015-08-31": 17439.226935,
                    "2015-09-30": 15969.581947,
                    "2015-10-31": 16650.800527,
                    "2015-11-30": 16811.612269,
                    "2015-12-31": 17157.343058,
                    "2016-01-31": 14822.688547,
                    "2016-02-29": 14742.953377,
                    "2016-03-31": 15071.84792,
                    "2016-04-30": 15321.012033,
                    "2016-05-31": 15856.714638,
                    "2016-06-30": 15709.705583,
                    "2016-07-31": 16454.704716,
                    "2016-08-31": 15946.40841,
                    "2016-09-30": 16158.198142,
                    "2016-10-31": 14907.405388,
                    "2016-11-30": 15674.824409,
                    "2016-12-31": 15382.043423,
                    "2017-01-31": 16137.086476,
                    "2017-02-28": 17264.446608,
                    "2017-03-31": 17113.437049,
                    "2017-04-30": 17509.183622,
                    "2017-05-31": 17389.419709,
                    "2017-06-30": 18389.199776,
                    "2017-07-31": 18680.800518,
                    "2017-08-31": 19107.787996,
                    "2017-09-30": 19360.341161,
                    "2017-10-31": 19222.347461,
                    "2017-11-30": 19750.878546,
                    "2017-12-31": 19681.083018,
                    "2018-01-31": 21356.839298,
                    "2018-02-28": 20321.732502,
                    "2018-03-31": 19946.851119,
                    "2018-04-30": 20000.00948,
                    "2018-05-31": 20878.451975,
                    "2018-06-30": 21205.76812,
                    "2018-07-31": 22003.081905,
                    "2018-08-31": 23373.904008
                  }
                }
                
                
## Fund Risk [/risk/fund_symbol]

### GET: /risk/fund_symbol [GET]

### Retrieves the following fields of risk data for the given mutual fund:
1. Alpha
2. Beta
3. R-squared
4. Standard deviation
5. Sharpe ratio
6. Sortino ratio
7. Treynor ratio
8. Capture ratios

...retrieves the above 8 fields for 3 years, 5 years, 10 years, 15 years.


### Sources I scraped this data from:
1. [Morningstar Risk MPT Stats](http://performance.morningstar.com/ratrisk/RatingRisk/fund/mpt-statistics.action?&t=PRHSX&region=usa&culture=en-US&cur=&ops=clear&s=0P00001L8R&y=3&ep=true&comparisonRemove=true&benchmarkSecId=&benchmarktype=)
2. [Morningstar Volatility Measurements](http://performance.morningstar.com/ratrisk/RatingRisk/fund/volatility-measurements.action?&t=PRHSX&region=usa&culture=en-US&cur=&ops=clear&s=0P00001L8R&y=3&ep=true&comparisonRemove=true&benchmarkSecId=&benchmarktype=)
3. [Morningstar Capture Ratios](http://performance.morningstar.com/ratrisk/RatingRisk/fund/updownside-capture.action?&t=PRHSX&region=usa&culture=en-US&cur=&ops=clear&s=0P00001L8R&ep=true&comparisonRemove=null&benchmarkSecId=&benchmarktype=)

**HTTP Request:**
`link coming soon once I deploy`

+ Response 200 (application/json)

    + Body
    
            {
              "3-Year": {
                "Upside Ratio": "115.08",
                "Downside ratio": "155.16",
                "Category Index": "Morningstar US Healthcare TR USD",
                "R-Squared": "87.76",
                "Beta": "1.13",
                "Alpha": "-2.11",
                "Treynor Ratio": "—",
                "Currency": "USD",
                "Standard Deviation": "15.47",
                "Return": "10.26",
                "Sharpe Ratio": "0.66",
                "Sortino Ratio": "0.92"
              },
              "5-Year": {
                "Upside Ratio": "115.13",
                "Downside ratio": "45.79",
                "Category Index": "MSCI ACWI NR USD",
                "R-Squared": "31.29",
                "Beta": "0.84",
                "Alpha": "9.94",
                "Treynor Ratio": "21.37",
                "Currency": "USD",
                "Standard Deviation": "15.01",
                "Return": "18.51",
                "Sharpe Ratio": "1.18",
                "Sortino Ratio": "1.84"
              },
              "10-Year": {
                "Upside Ratio": "108.81",
                "Downside ratio": "56.13",
                "Category Index": "MSCI ACWI NR USD",
                "R-Squared": "55.34",
                "Beta": "0.79",
                "Alpha": "11.71",
                "Treynor Ratio": "22.08",
                "Currency": "USD",
                "Standard Deviation": "17.39",
                "Return": "17.77",
                "Sharpe Ratio": "1.01",
                "Sortino Ratio": "1.55"
              },
              "15-Year": {
                "Upside Ratio": "99.90",
                "Downside ratio": "54.76",
                "Category Index": "MSCI ACWI NR USD",
                "R-Squared": "51.46",
                "Beta": "0.77",
                "Alpha": "8.89",
                "Treynor Ratio": "19.01",
                "Currency": "USD",
                "Standard Deviation": "15.66",
                "Return": "15.85",
                "Sharpe Ratio": "0.94",
                "Sortino Ratio": "1.45"
              }
            }
            
## General Stats [/general/fund_symbol]

### GET: /general/fund_symbol [GET]

### Retrieves the following fields of data for the given Genermutual fund:
1. Price (NAV)
2. Min. initial investment
3. Expense ratio
4. Asset allocation pie chart data (Morningstar's pie chart: Cash, US stock, Non-US stock, bonds, etc)
5. Morningstar overall rating
6. Morningstar risk vs category
7. Morningstar return vs category
8. Morningstar category
9. Turnover ratio

### Sources I scraped this data from:
1. [Morningstar General Stats](https://quotes.morningstar.com/fundq/c-header?&t=PRHSX&region=usa&culture=en-US&version=RET&cur=&test=QuoteiFrame)
2. [Morningstar Asset Allocation](https://quotes.morningstar.com/fundq/c-assetAllocation?&t=PRHSX&region=usa&culture=en-US&version=RET&cur=&test=QuoteiFrame)
3. [Morningstar Risk & Return vs Category](https://quotes.morningstar.com/fundq/c-risk-measures?&t=PRHSX&region=usa&culture=en-US&version=RET&cur=&test=QuoteiFrame)
4. [Morningstar Overall Rating](https://www.morningstar.com/api/v1/security-identifier/0P00002WFU)
5. [Morningstar Quotes](https://www.morningstar.com/funds/XNAS/PRHSX/quote.html)

**HTTP Request:**
`link coming soon once I deploy`

+ Response 200 (application/json)

    + Body
    
            {
              "Section.GENERAL_STATS": {
                "NAV": "81.82",
                "MinInvestment": "2,500",
                "ExpenseRatio": "0.77%",
                "Turnover": "38%",
                "MorningstarCategory": "Health"
              },
              "Section.ASSET_ALLOCATION": {
                "Cash": "0.38%",
                "US Stock": "93.99%",
                "Non US Stock": "5.17%",
                "Bond": "0.00%",
                "Other": "0.46%"
              },
              "Section.RISK_RETURN_VS_CATEGORY": {
                "Risk vs.Category": "Avg",
                "Return vs.Category": "High"
              },
              "Section.OVERALL_RATING": {
                "starRating": 4
              }
            }
            
## Holdings Stats [/holdings/fund_symbol]

### GET: /holdings/fund_symbol [GET]

### Retrieves the top 25 securities that comprise the fund, and the following fields from each of them:
1. Name
2. Percentage of portolio this security comprises
3. YTD return
4. Shares owned
5. Shares changed
6. P/E
7. Price
8. G/L % (gain/loss percent for the day)

### Sources I scraped this data from:
1. [Morningstar Top 25 Holdings](http://portfolios.morningstar.com/portfo/fund/ajax/holdings_tab?t=PRHSX&region=usa&culture=en-US&cur=&dataType=0&sortby=weighting&order=des)

**HTTP Request:**
`link coming soon once I deploy`

+ Response 200 (application/json)

    + Body
    
            {
              "UnitedHealth Group Inc": {
                "% portfolio weight": "7.68",
                "Shares Owned": "3,630,200",
                "Country": "United States",
                "YTD Return": "20.85",
                "P/E ratio": "21.95",
                "Currency": "USD",
                "Price": "263.29",
                "Gain/Loss %": "-0.22"
              },
              "Becton, Dickinson and Co": {
                "% portfolio weight": "5.04",
                "Shares Owned": "2,440,110",
                "Country": "United States",
                "YTD Return": "21.22",
                "P/E ratio": "102.48",
                "Currency": "USD",
                "Price": "259.75",
                "Gain/Loss %": "0.98"
              },
              "Intuitive Surgical Inc": {
                "% portfolio weight": "4.97",
                "Shares Owned": "1,205,326",
                "Country": "United States",
                "YTD Return": "53.08",
                "P/E ratio": "82.64",
                "Currency": "USD",
                "Price": "564.82",
                "Gain/Loss %": "1.10"
              },
              "Vertex Pharmaceuticals Inc": {
                "% portfolio weight": "3.69",
                "Shares Owned": "2,516,690",
                "Country": "United States",
                "YTD Return": "17.31",
                "P/E ratio": "110.57",
                "Currency": "USD",
                "Price": "177.12",
                "Gain/Loss %": "0.75"
              },
              "Anthem Inc": {
                "% portfolio weight": "2.92",
                "Shares Owned": "1,421,000",
                "Country": "United States",
                "YTD Return": "20.83",
                "P/E ratio": "16.41",
                "Currency": "USD",
                "Price": "270.97",
                "Gain/Loss %": "0.50"
              },
              "Stryker Corp": {
                "% portfolio weight": "2.61",
                "Shares Owned": "1,792,219",
                "Country": "United States",
                "YTD Return": "10.32",
                "P/E ratio": "60.03",
                "Currency": "USD",
                "Price": "174.10",
                "Gain/Loss %": "2.48"
              },
              "Alexion Pharmaceuticals Inc": {
                "% portfolio weight": "2.60",
                "Shares Owned": "2,425,595",
                "Country": "United States",
                "YTD Return": "-1.49",
                "P/E ratio": "—",
                "Currency": "USD",
                "Price": "120.82",
                "Gain/Loss %": "2.56"
              },
              "Sage Therapeutics Inc": {
                "% portfolio weight": "2.51",
                "Shares Owned": "1,856,661",
                "Country": "United States",
                "YTD Return": "-11.89",
                "P/E ratio": "—",
                "Currency": "USD",
                "Price": "146.96",
                "Gain/Loss %": "1.26"
              },
              "Thermo Fisher Scientific Inc": {
                "% portfolio weight": "2.34",
                "Shares Owned": "1,312,599",
                "Country": "United States",
                "YTD Return": "25.85",
                "P/E ratio": "40.24",
                "Currency": "USD",
                "Price": "239.10",
                "Gain/Loss %": "0.27"
              },
              "Cigna Corp": {
                "% portfolio weight": "2.27",
                "Shares Owned": "1,551,081",
                "Country": "United States",
                "YTD Return": "-2.57",
                "P/E ratio": "19.15",
                "Currency": "USD",
                "Price": "200.07",
                "Gain/Loss %": "1.13"
              },
              "Centene Corp": {
                "% portfolio weight": "2.13",
                "Shares Owned": "2,006,234",
                "Country": "United States",
                "YTD Return": "40.51",
                "P/E ratio": "24.23",
                "Currency": "USD",
                "Price": "142.84",
                "Gain/Loss %": "0.77"
              },
              "Agilent Technologies Inc": {
                "% portfolio weight": "2.05",
                "Shares Owned": "3,844,848",
                "Country": "United States",
                "YTD Return": "3.60",
                "P/E ratio": "75.91",
                "Currency": "USD",
                "Price": "68.93",
                "Gain/Loss %": "-0.22"
              },
              "Neurocrine Biosciences Inc": {
                "% portfolio weight": "1.99",
                "Shares Owned": "2,350,166",
                "Country": "United States",
                "YTD Return": "51.26",
                "P/E ratio": "—",
                "Currency": "USD",
                "Price": "120.26",
                "Gain/Loss %": "2.47"
              },
              "Sarepta Therapeutics Inc": {
                "% portfolio weight": "1.84",
                "Shares Owned": "1,611,512",
                "Country": "United States",
                "YTD Return": "173.81",
                "P/E ratio": "—",
                "Currency": "USD",
                "Price": "153.58",
                "Gain/Loss %": "0.81"
              },
              "Merck & Co Inc": {
                "% portfolio weight": "1.73",
                "Shares Owned": "3,302,683",
                "Country": "United States",
                "YTD Return": "27.71",
                "P/E ratio": "140.84",
                "Currency": "USD",
                "Price": "70.42",
                "Gain/Loss %": "0.00"
              },
              "Humana Inc": {
                "% portfolio weight": "1.70",
                "Shares Owned": "662,953",
                "Country": "United States",
                "YTD Return": "34.86",
                "P/E ratio": "34.23",
                "Currency": "USD",
                "Price": "335.99",
                "Gain/Loss %": "0.58"
              },
              "Danaher Corp": {
                "% portfolio weight": "1.53",
                "Shares Owned": "1,793,000",
                "Country": "United States",
                "YTD Return": "14.51",
                "P/E ratio": "28.11",
                "Currency": "USD",
                "Price": "106.76",
                "Gain/Loss %": "0.75"
              },
              "HCA Healthcare Inc": {
                "% portfolio weight": "1.49",
                "Shares Owned": "1,684,393",
                "Country": "United States",
                "YTD Return": "52.27",
                "P/E ratio": "16.65",
                "Currency": "USD",
                "Price": "133.78",
                "Gain/Loss %": "0.81"
              },
              "Biogen Inc": {
                "% portfolio weight": "1.40",
                "Shares Owned": "560,224",
                "Country": "United States",
                "YTD Return": "4.97",
                "P/E ratio": "23.67",
                "Currency": "USD",
                "Price": "336.89",
                "Gain/Loss %": "0.74"
              },
              "Incyte Corp": {
                "% portfolio weight": "1.40",
                "Shares Owned": "2,421,428",
                "Country": "United States",
                "YTD Return": "-29.24",
                "P/E ratio": "—",
                "Currency": "USD",
                "Price": "67.82",
                "Gain/Loss %": "1.19"
              },
              "Hologic Inc": {
                "% portfolio weight": "1.36",
                "Shares Owned": "3,957,700",
                "Country": "United States",
                "YTD Return": "-7.53",
                "P/E ratio": "—",
                "Currency": "USD",
                "Price": "40.50",
                "Gain/Loss %": "2.45"
              },
              "Regeneron Pharmaceuticals Inc": {
                "% portfolio weight": "1.31",
                "Shares Owned": "441,263",
                "Country": "United States",
                "YTD Return": "2.80",
                "P/E ratio": "28.01",
                "Currency": "USD",
                "Price": "388.33",
                "Gain/Loss %": "0.48"
              },
              "AstraZeneca PLC ADR": {
                "% portfolio weight": "1.26",
                "Shares Owned": "4,172,500",
                "Country": "United Kingdom",
                "YTD Return": "12.28",
                "P/E ratio": "35.60",
                "Currency": "USD",
                "Price": "37.49",
                "Gain/Loss %": "-0.19"
              },
              "bluebird bio Inc": {
                "% portfolio weight": "1.26",
                "Shares Owned": "932,281",
                "Country": "United States",
                "YTD Return": "-22.96",
                "P/E ratio": "—",
                "Currency": "USD",
                "Price": "140.00",
                "Gain/Loss %": "2.04"
              },
              "Biomarin Pharmaceutical Inc": {
                "% portfolio weight": "1.19",
                "Shares Owned": "1,466,067",
                "Country": "United States",
                "YTD Return": "10.07",
                "P/E ratio": "—",
                "Currency": "USD",
                "Price": "99.56",
                "Gain/Loss %": "1.44"
              }
            }